### ISSUE TITLE
Easy of use - enhance check if checkpoints is there - allow for download and install.

### ISSUE THREAD

**Issue by deeppppp** [private-dreamnet/dreamtime#11]
GUI: check if the cli\checkpoints folder with content is present and if not show an option to download it and automatically place the checkpoints folder and contents in correct location.

Equal for CLI; check if the  cli\checkpoints folder with content is present and if not show an option to download it and automatically place the checkpoints folder and contents in correct location.

**Comment by deeppppp** [comment]
Perhaps showing a video on how to install that includes the download of checkpoints would suffice.

**Comment by wisp101** [comment]
How would the app download the files? I see really old mega api clients occasionally, so that shouldn't be too bad. But mediafire (i think) is going to be a pain. I don't think we should try torrenting the checkpoints. Also, what if the checkpoints change/ are taken down? Do we host a link to the checkpoints, or just bake the url into the app itself?
