### ISSUE TITLE
QOL: Detect if WIndows N version and display custom error message

### ISSUE THREAD

**Issue by deeppppp** [private-dreamnet/dreamtime#16]
N versions of Windows 10 require installing the Media Feature Pack.

Can we do a version check and customize the error message do point users to the Media Feature Pack instead of the generic message they get now?

Reading the instructions that mention the Windows N issue is hard :)
and users may not even know their version of Windows.

**Comment by deep-man-yy** [comment]
The problem is knowing what exactly we have to verify, that is, we can verify that the version of Windows is N but obviously we do not want to give "an error message" even if they have already installed the Media Pack. What are the files that differentiate between a version without the Media Feature Pack and a version with the Pack?

**Comment by wisp101** [comment]
[This answer](https://stackoverflow.com/questions/25817449/how-to-detect-windows-media-pack-installed-on-system) might help if we decide to pursue this.

**Comment by kolesias** [comment]
> [This answer](https://stackoverflow.com/questions/25817449/how-to-detect-windows-media-pack-installed-on-system) might help if we decide to pursue this.

Perfect, thanks
