### ISSUE TITLE
Arch Linux additional steps for Ubuntu binaries

### ISSUE THREAD

**Issue by deeppppp** [private-dreamnet/dreamtime#37]
at first 'chrome-sandbox' may not be present in gui directory; it will appear after running CLI once.
from main directory 
1) cd cli
2) sudo chmod +x ./cli
3) ./cli --help
4) cd ../gui
5) sudo chown -R root:root chrome-sandbox
6) sudo chmod +4755 chrome-sandbox
7) chmod +x DreamTime

now the GUI should work.

**Comment by wisp101** [comment]
I think thats for most linux platforms too

**Comment by ringo-nine** [comment]
the chrome-sandox part wasn't required on ubuntu 18

**Comment by PommeDroid** [comment]
This bug normally occurs on linux kernel that doesn't have support for User Namespaces i.e. a kernel without CONFIG_USER_NS support or not enable. For archlinux if you using linux-hardened it's disable otherwise other Arch Kernel flavour should work (it works direclty on mine Arch). 

Two solutions to the problem:
 * Setting the right of the sandbox to root (as proposed by @deeppppp) : 

       sudo chown -R root:root chrome-sandbox
       sudo chmod +4755 chrome-sandbox

* Enable the sysctl setting kernel.unprivileged_userns_clone to allow normal users to run the sandbox:

  _Step 1 - Check your kernel support for User Namespaces:_
    Depending on your distribution:

       zgrep CONFIG_NAMESPACES /proc/config.gz

    or

      zgrep CONFIG_NAMESPACES /boot/config-$(uname -a | awk '{print $3}')

    If nothing is return by this command you need to activate the support by changing of kernel. Either by installing an other kernel flavour offered by your distribution with the support enable or by compiling a kernel yourself with the support enable .

  _Step 2 - Enable the option for User Namespaces:_

    Temporally enable the option:

       sudo sysctl kernel.unprivileged_userns_clone=1

    Permanently enable the option:

       sudo sh -c 'echo "1" > /proc/sys/kernel/unprivileged_userns_clone'
