### ISSUE TITLE
An error has Ocurred

### ISSUE THREAD

**Issue by Kaatelars** [private-dreamnet/dreamtime#73]
Always is present this problem in W10 x64
![image](https://user-images.githubusercontent.com/15205939/63720970-ec8c5900-c815-11e9-86c3-f7d78c49c107.png)

**Comment by anujpowerbox** [comment]
same issue on Ubuntu 18.04.3 LTS x64

**Comment by Akhlys** [comment]
Same on Linux Mint (not sure which version, I think 14) and my win 10.

Happens after first start (not subsequent starts, both win and linux) and half way in between getting the checkpoint (only on linux, after DL, at start of install, progress exactly 50%)
windows exited and re-opened the program during checkpoint update, but that may be intentional. "dreamifying" on windows still worked

win 10 error url firststart: https://rollbar.com/occurrence/uuid/?uuid=61ca91b3-ed0d-436f-d5a5-212f9fa541f5
don't have the other ones anymore

note:

**Comment by H-mmer** [comment]
Same problem on windows 10. https://rollbar.com/occurrence/uuid/?uuid=dba181e7-b244-4df1-d85b-0663789b05b3
