### ISSUE TITLE
Windows 8.1 error

### ISSUE THREAD

**Issue by Erremanf** [private-dreamnet/dreamtime#79]
Hello. So I tried processing the first image but I get this error:

> No error messages generated.
 FormatMessageW: The parameter is incorrect.

 LoadLibrary: PyInstaller: FormatMessageW failed.
> Error loading Python DLL 'C:\Users\User\AppData\Local\Programs\DreamTime\cli\python36.dll'.
> No error messages generated.
 FormatMessageW: The parameter is incorrect.

 LoadLibrary: PyInstaller: FormatMessageW failed.
> Error loading Python DLL 'C:\Users\User\AppData\Local\Programs\DreamTime\cli\python36.dll'.

**Enviroment (please complete the following information):**
 - Version  1.1.0
 - OS: Windows 8.1
 - Report URL: https://rollbar.com/occurrence/uuid/?uuid=d304b530-34cd-41b1-bca3-1729845013bd

Thanks in advance.

**Comment by kolessios** [comment]
The error message indicates that DreamPower was unable to load files necessary for its operation. This is probably caused because your operating system is missing updates or libraries.

This user had a similar problem with another program and also had Windows 8.1, you can try what he said:
https://bitcointalk.org/index.php?topic=2833220.msg29092606#msg29092606

`python3.dll` or `python36.dll` must be located in the DreamPower folder. (About -> DreamPower -> App Folder)
