### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by portalrule123** [private-dreamnet/dreamtime#94]
An error has occurred!
Oops! An unknown error has awakened us from our dreams, we will try to solve it in the next version.

Experienced immediately after starting dream time after a fresh install.

 - Version v1.1.0
 - OS: Windows 10
 - Report URL: https://rollbar.com/occurrence/uuid/?uuid=8cefe24d-3707-406d-c2d6-712b2788cc7e

Any idea of how to fix this? Is it just a bad installer that a re-download may be able to fix?

**Comment by kolessios** [comment]
Do not worry, we know about this error and it only happens as you say when you run DreamTime for the first time, this error should not affect anything else.

**Comment by nmnrna** [comment]
The issue only affects the first time? I am affected by this every time I open DreamTime v1.1.0 on my windows 10 laptop.

**Comment by kolessios** [comment]
> The issue only affects the first time? I am affected by this every time I open DreamTime v1.1.0 on my windows 10 laptop.

The same error message? For now we only had reports that it appeared when installed, just after accepting the welcome message.

**Comment by nmnrna** [comment]
I closed the s/w by accident while it was downloading the checkpoint update. Now, the checkpoints update starts from 50% with high disk usage, increases to 75% and then gets stuck at 100%. After some time the error message shows up and every processor/disk usage from it stops.

**Comment by nmnrna** [comment]
100.00% - 0.00/0.00 MB - (Please do not close the program or leave this section)

**Comment by kolessios** [comment]
It is very possible that the downloaded file is corrupt so DreamTime has a hard time "installing it" (unzipping it) and ends with an error. You can fix it by deleting the file `v0.0.1.zip` from the Downloads folder of your operating system. If you think that DreamTime has problems downloading the file you can download it manually with the `Download` button (right next to `Update`) and then place the `.zip` in the Downloads folder so that DreamTime uses it instead of download it

**Comment by nmnrna** [comment]
Yes, figured it out. The zip file was indeed corrupt. Deleted it and the download started again just fine. I also removed the cm.lib mm.lib and mn.lib from the checkpoints folder just to be sure. Downloading 1.9 GB again. Let's see.
